### ISSUE TITLE
macOS specialKey+Enter to send

### ISSUE THREAD

**Issue by jonasbits** [jneilliii/OctoPrint-MultiLineTerminal#1]
thanks for this plug-in, it works, but i want to help iron out the Enter functionallity

i have a mac, so i maybe cmd+Enter sends all the gcode lines to be processed...
maybe CTRL+Enter on pc...

right now its a little unknown if i will get a new line to type at, or if its going to be sent anyway.

Thanks for your work, hope this will be included in the Plug-in repository soon!

**Comment by jonasbits** [comment]
found at https://community.octoprint.org/t/plugin-idea-multiline-terminal-input/19569/4

**Comment by jneilliii** [comment]
So this one is something that I stripped away from the multiline text field because you don't want to send the commands when you hit enter. With this plugin installed you must use the send button. 

Prepping the release for the plugin repo now.

**Comment by DocYester** [comment]
we dont want to hit enter to send them, but ctrl+enter (on pc) or cmd+enter (on mac)
it's a little bit annoying to put some lines together with the keyboard and then take the mouse again to send them
that's what @jonasbits means

**Comment by jneilliii** [comment]
I just pushed an update that enables shift+enter and adds command history. Hopefully that appeases you guys. Hopefully if you find that change useful you'll use the tip link on the readme.
