### ISSUE TITLE
Turns console case-sensitive

### ISSUE THREAD

**Issue by LeandroMarceddu** [jneilliii/OctoPrint-MultiLineTerminal#2]
Though this might not be a true issue; this plugin turns the console into case-sensitive; whereas the original console is not. Perhaps integrate original console's markup editor before sending?

**Comment by jneilliii** [comment]
This is true, I have not integrated any of the case logic as in the original. Will add this to the next release.

**Comment by jneilliii** [comment]
releasing updated version that adds blacklist processing and auto-capitalization like original terminal input
