### ISSUE TITLE
Command history binding support

### ISSUE THREAD

**Issue by Outpox** [jneilliii/OctoPrint-MultiLineTerminal#3]
Hey there and thanks for the plugin!
I really love it but I just had to disable it because having to manually click the up arrow to repeat the previous command is an issue for me when I'm calibrating my machine when I'm tweaking the same command over and over.
I would suggest adding a new event listener on shift key and up and down arrow (on the keyboard) that could trigger the history.  
I can make a PR if you want.

**Comment by jneilliii** [comment]
I don't see a reason why I couldn't do that. Just have to look up the codes for arrow up and arrow down.

**Comment by jneilliii** [comment]
just released a new version that takes away the buttons in preference of shift+up and shift+down

**Comment by Outpox** [comment]
Thanks!
