### ISSUE TITLE
[Request] Use arrow key "up" to edit last sent command

### ISSUE THREAD

**Issue by RayPS** [jneilliii/OctoPrint-MultiLineTerminal#9]
In the original Octoprint terminal, when the input box is empty, we can use "up" key to edit/resend the last command, wish this feature also implement in this addon.

**Comment by jneilliii** [comment]
I'm pretty sure it was.

**Comment by jneilliii** [comment]
Quoting the readme...

> Use shift+up and shift+down to navigate through command history while in multi-line mode.
